site_name: Molinfo
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
<<<<<<< HEAD
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: orange 
    - scheme: slate 
=======
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue
      accent: orange
    - scheme: slate
>>>>>>> c4f5d6f634eb8bb37285ee86c97872be334d0984
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue
      accent: yellow

<<<<<<< HEAD
=======

>>>>>>> c4f5d6f634eb8bb37285ee86c97872be334d0984
plugins:
  # - social
  - search
  - mkdocstrings

<<<<<<< HEAD
=======

>>>>>>> c4f5d6f634eb8bb37285ee86c97872be334d0984
# extra:
#   social:
#     - icon: fontawesome/brands/github-alt
#       link: https://github.com/sinagilassi
#     - icon: fontawesome/brands/linkedin
#       link: https://www.linkedin.com/in/sina-gilassi

<<<<<<< HEAD
=======

>>>>>>> c4f5d6f634eb8bb37285ee86c97872be334d0984
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

<<<<<<< HEAD
copyright: |
  &copy; 2024 <a href="https://github.com/sinagilassi"  target="_blank" rel="noopener">Sina Gilassi</a>
=======

copyright: |
  &copy; 2024 <a href="https://github.com/sinagilassi"  target="_blank" rel="noopener">Sina Gilassi</a>
>>>>>>> c4f5d6f634eb8bb37285ee86c97872be334d0984
